# Request
PathMsg 		        path
---
# Response
bool                    valid
int64                   nextValidPathSegment
int64                   nextValidPoint
bool[]                  stateValidity
geometry_msgs/Polygon   footprint