map:
  frame_id:     map
  layer_name:   traversability
  resolution:   1.0
  position:
    x:          10.0
    y:          0.0
  length:       20.0  # x dimension
  width:        20.0  # y dimension
obstacle:
  length:       1.0
  width:        0.5