map:
  frame_id:     map
  layer_name:   traversability
  resolution:   0.1
  position:
    x:          0.0
    y:          0.0
  length:       50.0  # x dimension
  width:        50.0  # y dimension
obstacle:
  length:       1.0
  width:        2.0