map:
  frame_id:     map
  layer_name:   traversability
  resolution:   0.1
  position:
    x:          5.0
    y:          0.0
  length:       20.0  # x dimension
  width:        20.0  # y dimension
obstacle:
  length:       1.0
  width:        1.0